# Generated by Django 4.0.6 on 2022-07-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_review_product_delete_product_delete_review'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE TABLE store_product (
                id serial,
                title varchar(255) NOT NULL ,
                price decimal(14, 3) NOT NULL CHECK ( price >= 0 ) ,
                inventory int NOT NULL CHECK ( inventory >= 0 ),
                last_update timestamp with time zone NOT NULL DEFAULT current_timestamp,
                primary key (id)
            );
        """, """
            DROP TABLE store_product;
        """)
    ]
