# Generated by Django 4.0.6 on 2022-07-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_create_store_product_table'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE TABLE store_review (
                id serial,
                product_id INT NOT NULL,
                content TEXT NOT NULL,
                review_date timestamp with time zone NOT NULL DEFAULT current_timestamp,
                rating INT NOT NULL CHECK ( rating >= 0 AND rating <= 5),
                PRIMARY KEY (id),
                CONSTRAINT fk_product
                    FOREIGN KEY (product_id)
                        REFERENCES store_product(id)
                        ON DELETE CASCADE
            );
        """, """
            DROP TABLE store_review;
        """)
    ]
