# Generated by Django 4.0.6 on 2022-07-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_create_store_review_table'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE TABLE store_customer(
                id serial,
                phone VARCHAR(255) NOT NULL,
                address TEXT NOT NULL,
                postal_code VARCHAR(255) NOT NULL,
                user_id INT NOT NULL UNIQUE,
                PRIMARY KEY (id),
                CONSTRAINT fk_user
                    FOREIGN KEY (user_id)
                    REFERENCES core_user(id)
                    ON DELETE CASCADE
            );
        """, """
            DROP TABLE store_customer;
        """)
    ]
