# Generated by Django 4.0.6 on 2022-07-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_create_store_customer_table'),
    ]

    operations = [
        migrations.RunSQL("""
            ALTER TABLE store_customer 
            ALTER COLUMN phone TYPE VARCHAR(255);
        """)
    ]
