# Generated by Django 4.0.6 on 2022-07-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_create_store_customer_table'),
    ]

    operations = [
        migrations.RunSQL("""
        CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
        CREATE TABLE store_cart (
            id VARCHAR(36) DEFAULT uuid_generate_v4 (),
            delivery_method VARCHAR(255) NOT NULL DEFAULT 'P' CHECK ( delivery_method IN ('P', 'V')),
            PRIMARY KEY (id)
        );
    """, """
        DROP TABLE store_cart;
    """)
    ]
