# Generated by Django 4.0.6 on 2022-07-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_change_store_customer_type_phone_to_varchar'),
    ]

    operations = [
        migrations.RunSQL("""
        CREATE TABLE store_cart (
            id SERIAL,
            PRIMARY KEY (id)
        );
    """, """
        DROP TABLE store_cart;
    """)
    ]
# total_price INT NOT NULL DEFAULT 0 CHECK ( total_price >= 0 ),