# Generated by Django 4.0.6 on 2022-07-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_change_store_customer_type_phone_to_varchar'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE TABLE store_cartitem (
                id SERIAL,
                product_id INT NOT NULL,
                quantity INT NOT NULL DEFAULT 1 CHECK ( quantity > 0 ),
                PRIMARY KEY (id),
                CONSTRAINT fk_product
                    FOREIGN KEY (product_id)
                    REFERENCES store_product(id)
                    ON DELETE CASCADE
            );
        """, """
            DROP TABLE store_cartitem;
        """)
    ]
