# Generated by Django 4.0.6 on 2022-07-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220711_2113'),
    ]

    operations = [
    ]
