# Generated by Django 4.0.6 on 2022-07-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_create_store_cartitem_table'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE TABLE store_order(
                id serial,
                price DECIMAL(14, 3) NOT NULL CHECK ( price >= 0 ),
                state VARCHAR(255) NOT NULL CHECK ( state IN ('P', 'C', 'F')),
                customer_id INT NOT NULL,
                created_at timestamp with time zone NOT NULL DEFAULT current_timestamp,
                PRIMARY KEY (id),
                CONSTRAINT fk_customer
                    FOREIGN KEY (customer_id)
                    REFERENCES store_customer(id)
            );
        """, """
            DROP TABLE store_order;
        """)
    ]
