# Generated by Django 4.0.6 on 2022-07-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_create_store_order_table'),
    ]

    operations = [
        migrations.RunSQL("""
        CREATE TABLE store_orderitem (
            id SERIAL,
            product_id INT NOT NULL,
            order_id INT NOT NULL,
            quantity INT NOT NULL DEFAULT 1 CHECK ( quantity > 0 ),
            PRIMARY KEY (id),
            CONSTRAINT fk_product
                FOREIGN KEY (product_id)
                REFERENCES store_product(id)
                ON DELETE CASCADE,
            CONSTRAINT fk_order
                FOREIGN KEY (order_id)
                REFERENCES store_order(id)
        );
        """, """
            DROP TABLE store_orderitem;
        """)
    ]
