# Generated by Django 4.0.6 on 2022-07-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_create_store_orderitem_table'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE TABLE store_category (
                id serial,
                name VARCHAR(255) NOT NULL,
                PRIMARY KEY (id)
            );
        """, """
            DROP TABLE store_category;
        """)
    ]
