# Generated by Django 4.0.6 on 2022-07-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_create_store_orderitem_table'),
    ]

    operations = [
        migrations.RunSQL("""
insert into store_product (title, price, inventory) values ('Pastry - Mini French Pastries', 339.425, 1);
insert into store_product (title, price, inventory) values ('Wine - Red, Lurton Merlot De', 535.586, 2);
insert into store_product (title, price, inventory) values ('Beer - True North Lager', 691.501, 3);
insert into store_product (title, price, inventory) values ('Egg - Salad Premix', 753.958, 4);
insert into store_product (title, price, inventory) values ('Phyllo Dough', 266.041, 5);
insert into store_product (title, price, inventory) values ('Appetizer - Lobster Phyllo Roll', 992.046, 6);
insert into store_product (title, price, inventory) values ('Trout - Rainbow, Frozen', 940.456, 7);
insert into store_product (title, price, inventory) values ('Mushroom - Porcini Frozen', 336.793, 8);
insert into store_product (title, price, inventory) values ('Cheese - Cheddar, Old White', 395.846, 9);
insert into store_product (title, price, inventory) values ('Mudslide', 975.958, 10);
insert into store_product (title, price, inventory) values ('Amaretto', 25.642, 11);
insert into store_product (title, price, inventory) values ('Salmon - Fillets', 11.835, 12);
insert into store_product (title, price, inventory) values ('Juice - Orangina', 112.405, 13);
insert into store_product (title, price, inventory) values ('Dragon Fruit', 837.97, 14);
insert into store_product (title, price, inventory) values ('Jameson Irish Whiskey', 885.668, 15);
insert into store_product (title, price, inventory) values ('General Purpose Trigger', 819.593, 16);
insert into store_product (title, price, inventory) values ('Foil - 4oz Custard Cup', 589.438, 17);
insert into store_product (title, price, inventory) values ('Aspic - Amber', 206.059, 18);
insert into store_product (title, price, inventory) values ('Fond - Neutral', 511.741, 19);
insert into store_product (title, price, inventory) values ('Langers - Mango Nectar', 872.958, 20);
insert into store_product (title, price, inventory) values ('Pail - 15l White, With Handle', 161.054, 21);
insert into store_product (title, price, inventory) values ('Taro Leaves', 651.867, 22);
insert into store_product (title, price, inventory) values ('Pepper - Roasted Red', 532.019, 23);
insert into store_product (title, price, inventory) values ('Tart Shells - Savory, 2', 388.411, 24);
insert into store_product (title, price, inventory) values ('Yeast Dry - Fleischman', 764.344, 25);
insert into store_product (title, price, inventory) values ('Wine - Manischewitz Concord', 347.706, 26);
insert into store_product (title, price, inventory) values ('Wine - White, Colubia Cresh', 506.008, 27);
insert into store_product (title, price, inventory) values ('Pan Grease', 336.092, 28);
insert into store_product (title, price, inventory) values ('Apple - Custard', 386.109, 29);
insert into store_product (title, price, inventory) values ('Wood Chips - Regular', 691.594, 30);
insert into store_product (title, price, inventory) values ('Wooden Mop Handle', 373.365, 31);
insert into store_product (title, price, inventory) values ('Foil - Round Foil', 710.325, 32);
insert into store_product (title, price, inventory) values ('Pop Shoppe Cream Soda', 22.316, 33);
insert into store_product (title, price, inventory) values ('Tomato Paste', 806.843, 34);
insert into store_product (title, price, inventory) values ('Cheese - Ermite Bleu', 742.28, 35);
insert into store_product (title, price, inventory) values ('Baking Powder', 727.778, 36);
insert into store_product (title, price, inventory) values ('Cookies - Fortune', 132.284, 37);
insert into store_product (title, price, inventory) values ('Vodka - Hot, Lnferno', 31.337, 38);
insert into store_product (title, price, inventory) values ('Table Cloth 62x120 Colour', 749.515, 39);
insert into store_product (title, price, inventory) values ('Beef - Eye Of Round', 17.371, 40);
insert into store_product (title, price, inventory) values ('Rice - 7 Grain Blend', 240.342, 41);
insert into store_product (title, price, inventory) values ('Marjoram - Fresh', 861.663, 42);
insert into store_product (title, price, inventory) values ('Olives - Black, Pitted', 614.43, 43);
insert into store_product (title, price, inventory) values ('Ice Cream Bar - Oreo Sandwich', 144.36, 44);
insert into store_product (title, price, inventory) values ('Venison - Denver Leg Boneless', 156.106, 45);
insert into store_product (title, price, inventory) values ('Ice Cream Bar - Oreo Sandwich', 310.582, 46);
insert into store_product (title, price, inventory) values ('Chips Potato Swt Chilli Sour', 637.036, 47);
insert into store_product (title, price, inventory) values ('Eggplant - Regular', 739.048, 48);
insert into store_product (title, price, inventory) values ('Muffin Mix - Oatmeal', 610.254, 49);
insert into store_product (title, price, inventory) values ('Mushroom Morel Fresh', 989.908, 50);
insert into store_product (title, price, inventory) values ('Arizona - Green Tea', 54.654, 51);
insert into store_product (title, price, inventory) values ('Apricots - Dried', 137.161, 52);
insert into store_product (title, price, inventory) values ('Sugar - Splenda Sweetener', 552.378, 53);
insert into store_product (title, price, inventory) values ('Foil - 4oz Custard Cup', 787.848, 54);
insert into store_product (title, price, inventory) values ('Bagelers - Cinn / Brown Sugar', 624.054, 55);
insert into store_product (title, price, inventory) values ('Muffin Mix - Banana Nut', 615.388, 56);
insert into store_product (title, price, inventory) values ('Allspice - Jamaican', 478.97, 57);
insert into store_product (title, price, inventory) values ('Tea - Lemon Green Tea', 201.946, 58);
insert into store_product (title, price, inventory) values ('Olives - Morracan Dired', 990.237, 59);
insert into store_product (title, price, inventory) values ('Rambutan', 213.455, 60);
insert into store_product (title, price, inventory) values ('Sole - Dover, Whole, Fresh', 333.248, 61);
insert into store_product (title, price, inventory) values ('Liqueur - Melon', 291.014, 62);
insert into store_product (title, price, inventory) values ('Icecream - Dstk Super Cone', 989.171, 63);
insert into store_product (title, price, inventory) values ('Muffin Hinge 117n', 46.677, 64);
insert into store_product (title, price, inventory) values ('Coconut - Creamed, Pure', 130.07, 65);
insert into store_product (title, price, inventory) values ('Wine - Puligny Montrachet A.', 984.62, 66);
insert into store_product (title, price, inventory) values ('Snapple Lemon Tea', 275.356, 67);
insert into store_product (title, price, inventory) values ('Rum - Spiced, Captain Morgan', 33.281, 68);
insert into store_product (title, price, inventory) values ('Wine - Two Oceans Sauvignon', 564.424, 69);
insert into store_product (title, price, inventory) values ('Container - Foam Dixie 12 Oz', 793.808, 70);
insert into store_product (title, price, inventory) values ('Veal - Bones', 431.297, 71);
insert into store_product (title, price, inventory) values ('Beef - Tender Tips', 61.609, 72);
insert into store_product (title, price, inventory) values ('Turkey - Breast, Smoked', 301.084, 73);
insert into store_product (title, price, inventory) values ('Beans - Kidney, Canned', 509.05, 74);
insert into store_product (title, price, inventory) values ('Spinach - Packaged', 384.904, 75);
insert into store_product (title, price, inventory) values ('Spice - Paprika', 128.783, 76);
insert into store_product (title, price, inventory) values ('Dome Lid Clear P92008h', 581.649, 77);
insert into store_product (title, price, inventory) values ('Limes', 567.784, 78);
insert into store_product (title, price, inventory) values ('Bread - Bagels, Mini', 421.278, 79);
insert into store_product (title, price, inventory) values ('Sole - Iqf', 784.855, 80);
insert into store_product (title, price, inventory) values ('Pepper - Sorrano', 108.556, 81);
insert into store_product (title, price, inventory) values ('Potatoes - Idaho 80 Count', 130.075, 82);
insert into store_product (title, price, inventory) values ('Turkey - Breast, Boneless Sk On', 311.03, 83);
insert into store_product (title, price, inventory) values ('Ice Cream - Vanilla', 326.047, 84);
insert into store_product (title, price, inventory) values ('Butter - Unsalted', 579.107, 85);
insert into store_product (title, price, inventory) values ('Sobe - Berry Energy', 618.393, 86);
insert into store_product (title, price, inventory) values ('Tomatoes - Cherry', 541.091, 87);
insert into store_product (title, price, inventory) values ('Lamb Shoulder Boneless Nz', 882.077, 88);
insert into store_product (title, price, inventory) values ('Yogurt - Blueberry, 175 Gr', 209.663, 89);
insert into store_product (title, price, inventory) values ('Okra', 648.723, 90);
insert into store_product (title, price, inventory) values ('Pork - Shoulder', 66.378, 91);
insert into store_product (title, price, inventory) values ('Wine - Riesling Alsace Ac 2001', 74.609, 92);
insert into store_product (title, price, inventory) values ('Cornstarch', 51.579, 93);
insert into store_product (title, price, inventory) values ('Icecream - Dibs', 277.625, 94);
insert into store_product (title, price, inventory) values ('Juice - Prune', 911.748, 95);
insert into store_product (title, price, inventory) values ('Wine - Ruffino Chianti Classico', 418.986, 96);
insert into store_product (title, price, inventory) values ('Kolrabi', 203.991, 97);
insert into store_product (title, price, inventory) values ('Chinese Foods - Cantonese', 203.286, 98);
insert into store_product (title, price, inventory) values ('Bread - Malt', 132.255, 99);
insert into store_product (title, price, inventory) values ('Ecolab - Medallion', 988.627, 100);
        """)
    ]
