# Generated by Django 4.0.6 on 2022-07-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_create_store_category_table'),
    ]

    operations = [
        migrations.RunSQL("""
            ALTER TABLE store_product
            ADD COLUMN category_id INT;
            ALTER TABLE store_product
            ADD CONSTRAINT fk_category
                FOREIGN KEY (category_id)
                REFERENCES store_category (id)
                ON DELETE RESTRICT;
        """, """
            ALTER TABLE store_product
            DROP COLUMN category_id;
         """)
    ]
