# Generated by Django 4.0.6 on 2022-07-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_add_store_dummy_data'),
    ]

    operations = [
        migrations.RunSQL("""
insert into store_product (title, price, inventory, category_id) values ('Tea - Lemon Green Tea', 648.573, 1, 7);
insert into store_product (title, price, inventory, category_id) values ('Seedlings - Clamshell', 999.812, 2, 2);
insert into store_product (title, price, inventory, category_id) values ('Island Oasis - Cappucino Mix', 46.868, 3, 14);
insert into store_product (title, price, inventory, category_id) values ('Compound - Raspberry', 821.714, 4, 5);
insert into store_product (title, price, inventory, category_id) values ('French Pastries', 684.161, 5, 12);
insert into store_product (title, price, inventory, category_id) values ('Cream - 18%', 960.947, 6, 9);
insert into store_product (title, price, inventory, category_id) values ('Coconut - Shredded, Sweet', 553.937, 7, 8);
insert into store_product (title, price, inventory, category_id) values ('Fish - Scallops, Cold Smoked', 462.865, 8, 13);
insert into store_product (title, price, inventory, category_id) values ('Pastrami', 701.164, 9, 6);
insert into store_product (title, price, inventory, category_id) values ('Island Oasis - Mango Daiquiri', 27.643, 10, 3);
insert into store_product (title, price, inventory, category_id) values ('Beer - True North Strong Ale', 975.52, 11, 13);
insert into store_product (title, price, inventory, category_id) values ('Persimmons', 399.259, 12, 6);
insert into store_product (title, price, inventory, category_id) values ('Soup - Campbells, Creamy', 669.583, 13, 2);
insert into store_product (title, price, inventory, category_id) values ('Chilli Paste, Sambal Oelek', 314.563, 14, 7);
insert into store_product (title, price, inventory, category_id) values ('Orange Roughy 6/8 Oz', 766.06, 15, 14);
insert into store_product (title, price, inventory, category_id) values ('Pastry - Carrot Muffin - Mini', 252.553, 16, 7);
insert into store_product (title, price, inventory, category_id) values ('Snapple - Iced Tea Peach', 876.222, 17, 11);
insert into store_product (title, price, inventory, category_id) values ('Carbonated Water - Blackberry', 811.12, 18, 6);
insert into store_product (title, price, inventory, category_id) values ('Beef - Tongue, Fresh', 922.389, 19, 15);
insert into store_product (title, price, inventory, category_id) values ('Yogurt - Plain', 573.4, 20, 11);
insert into store_product (title, price, inventory, category_id) values ('Rice Paper', 487.018, 21, 13);
insert into store_product (title, price, inventory, category_id) values ('Strawberries', 880.445, 22, 2);
insert into store_product (title, price, inventory, category_id) values ('Cranberry Foccacia', 245.39, 23, 6);
insert into store_product (title, price, inventory, category_id) values ('Beer - Mcauslan Apricot', 404.155, 24, 4);
insert into store_product (title, price, inventory, category_id) values ('Pasta - Penne Primavera, Single', 818.739, 25, 10);
insert into store_product (title, price, inventory, category_id) values ('Alize Sunset', 41.083, 26, 12);
insert into store_product (title, price, inventory, category_id) values ('Pastry - Trippleberry Muffin - Mini', 367.439, 27, 1);
insert into store_product (title, price, inventory, category_id) values ('Bread - Raisin Walnut Oval', 877.514, 28, 6);
insert into store_product (title, price, inventory, category_id) values ('Salt - Seasoned', 743.021, 29, 8);
insert into store_product (title, price, inventory, category_id) values ('Wine - Duboeuf Beaujolais', 100.535, 30, 15);
insert into store_product (title, price, inventory, category_id) values ('Salt - Celery', 149.931, 31, 4);
insert into store_product (title, price, inventory, category_id) values ('Towel Dispenser', 131.137, 32, 1);
insert into store_product (title, price, inventory, category_id) values ('Trout - Smoked', 48.808, 33, 1);
insert into store_product (title, price, inventory, category_id) values ('Cranberries - Dry', 426.597, 34, 7);
insert into store_product (title, price, inventory, category_id) values ('Broom - Angled', 91.433, 35, 13);
insert into store_product (title, price, inventory, category_id) values ('Glass Clear 7 Oz Xl', 311.8, 36, 5);
insert into store_product (title, price, inventory, category_id) values ('Wheat - Soft Kernal Of Wheat', 540.294, 37, 6);
insert into store_product (title, price, inventory, category_id) values ('Squash - Pepper', 441.168, 38, 9);
insert into store_product (title, price, inventory, category_id) values ('Pasta - Elbows, Macaroni, Dry', 506.581, 39, 11);
insert into store_product (title, price, inventory, category_id) values ('White Fish - Filets', 85.86, 40, 14);
insert into store_product (title, price, inventory, category_id) values ('Cardamon Seed / Pod', 312.607, 41, 12);
insert into store_product (title, price, inventory, category_id) values ('Flour - Buckwheat, Dark', 678.483, 42, 9);
insert into store_product (title, price, inventory, category_id) values ('Veal - Knuckle', 28.202, 43, 3);
insert into store_product (title, price, inventory, category_id) values ('Fork - Plastic', 435.077, 44, 2);
insert into store_product (title, price, inventory, category_id) values ('Carroway Seed', 686.716, 45, 7);
insert into store_product (title, price, inventory, category_id) values ('Lamb Rack Frenched Australian', 736.886, 46, 3);
insert into store_product (title, price, inventory, category_id) values ('Versatainer Nc - 8288', 613.317, 47, 6);
insert into store_product (title, price, inventory, category_id) values ('Soup - Campbells Mac N Cheese', 550.507, 48, 1);
insert into store_product (title, price, inventory, category_id) values ('Croissants Thaw And Serve', 98.412, 49, 12);
insert into store_product (title, price, inventory, category_id) values ('Muffin - Carrot Individual Wrap', 899.149, 50, 3);
insert into store_product (title, price, inventory, category_id) values ('Pepsi - 600ml', 48.586, 51, 4);
insert into store_product (title, price, inventory, category_id) values ('Soup Campbells', 719.093, 52, 14);
insert into store_product (title, price, inventory, category_id) values ('Water - Spring Water 500ml', 658.811, 53, 5);
insert into store_product (title, price, inventory, category_id) values ('Pepper - Roasted Red', 143.895, 54, 2);
insert into store_product (title, price, inventory, category_id) values ('Bouillion - Fish', 898.35, 55, 3);
insert into store_product (title, price, inventory, category_id) values ('The Pop Shoppe - Grape', 722.209, 56, 13);
insert into store_product (title, price, inventory, category_id) values ('Bandage - Flexible Neon', 252.181, 57, 3);
insert into store_product (title, price, inventory, category_id) values ('Pasta - Lasagna Noodle, Frozen', 308.85, 58, 9);
insert into store_product (title, price, inventory, category_id) values ('Container - Hngd Cll Blk 7x7x3', 459.884, 59, 8);
insert into store_product (title, price, inventory, category_id) values ('Yokaline', 236.048, 60, 4);
insert into store_product (title, price, inventory, category_id) values ('Bread - Olive', 719.457, 61, 12);
insert into store_product (title, price, inventory, category_id) values ('Banana - Leaves', 441.27, 62, 10);
insert into store_product (title, price, inventory, category_id) values ('Coffee Guatemala Dark', 976.466, 63, 5);
insert into store_product (title, price, inventory, category_id) values ('Ham - Smoked, Bone - In', 885.284, 64, 9);
insert into store_product (title, price, inventory, category_id) values ('Soup - Campbells, Chix Gumbo', 604.165, 65, 10);
insert into store_product (title, price, inventory, category_id) values ('Cheese - Pied De Vents', 73.34, 66, 4);
insert into store_product (title, price, inventory, category_id) values ('Chips - Miss Vickies', 463.371, 67, 2);
insert into store_product (title, price, inventory, category_id) values ('Parsley - Fresh', 519.836, 68, 14);
insert into store_product (title, price, inventory, category_id) values ('Ecolab - Balanced Fusion', 905.579, 69, 2);
insert into store_product (title, price, inventory, category_id) values ('Nougat - Paste / Cream', 610.395, 70, 1);
insert into store_product (title, price, inventory, category_id) values ('Radish - Pickled', 562.513, 71, 4);
insert into store_product (title, price, inventory, category_id) values ('Potatoes - Purple, Organic', 768.128, 72, 2);
insert into store_product (title, price, inventory, category_id) values ('Cranberries - Fresh', 632.805, 73, 9);
insert into store_product (title, price, inventory, category_id) values ('Napkin - Cocktail,beige 2 - Ply', 449.396, 74, 11);
insert into store_product (title, price, inventory, category_id) values ('Oneshot Automatic Soap System', 458.38, 75, 6);
insert into store_product (title, price, inventory, category_id) values ('Rolled Oats', 669.216, 76, 1);
insert into store_product (title, price, inventory, category_id) values ('Icecream Cone - Areo Chocolate', 572.082, 77, 5);
insert into store_product (title, price, inventory, category_id) values ('Praline Paste', 635.867, 78, 4);
insert into store_product (title, price, inventory, category_id) values ('Beef - Rib Roast, Capless', 804.968, 79, 9);
insert into store_product (title, price, inventory, category_id) values ('Lemonade - Black Cherry, 591 Ml', 609.708, 80, 4);
insert into store_product (title, price, inventory, category_id) values ('Bread Sour Rolls', 978.245, 81, 2);
insert into store_product (title, price, inventory, category_id) values ('Cheese - Mozzarella', 145.182, 82, 7);
insert into store_product (title, price, inventory, category_id) values ('Tea - Green', 541.743, 83, 13);
insert into store_product (title, price, inventory, category_id) values ('Wine - Two Oceans Sauvignon', 144.037, 84, 4);
insert into store_product (title, price, inventory, category_id) values ('Cheese - Blue', 545.172, 85, 5);
insert into store_product (title, price, inventory, category_id) values ('Chocolate - Semi Sweet, Calets', 210.271, 86, 8);
insert into store_product (title, price, inventory, category_id) values ('White Baguette', 868.862, 87, 6);
insert into store_product (title, price, inventory, category_id) values ('Yogurt - Blueberry, 175 Gr', 840.874, 88, 3);
insert into store_product (title, price, inventory, category_id) values ('Coffee Cup 12oz 5342cd', 152.701, 89, 10);
insert into store_product (title, price, inventory, category_id) values ('Extract - Rum', 14.107, 90, 4);
insert into store_product (title, price, inventory, category_id) values ('Beef - Roasted, Cooked', 265.227, 91, 13);
insert into store_product (title, price, inventory, category_id) values ('Parsley Italian - Fresh', 857.555, 92, 1);
insert into store_product (title, price, inventory, category_id) values ('Spice - Peppercorn Melange', 962.67, 93, 7);
insert into store_product (title, price, inventory, category_id) values ('Rice - Aborio', 206.194, 94, 12);
insert into store_product (title, price, inventory, category_id) values ('Table Cloth 90x90 Colour', 663.319, 95, 9);
insert into store_product (title, price, inventory, category_id) values ('Cream Of Tartar', 981.653, 96, 12);
insert into store_product (title, price, inventory, category_id) values ('Soup - Campbells Bean Medley', 180.05, 97, 10);
insert into store_product (title, price, inventory, category_id) values ('Chips Potato Swt Chilli Sour', 302.479, 98, 6);
insert into store_product (title, price, inventory, category_id) values ('Wiberg Cure', 344.057, 99, 15);
insert into store_product (title, price, inventory, category_id) values ('Iced Tea - Lemon, 460 Ml', 490.625, 100, 9);
        """, """ SELECT * FROM store_product """)
    ]
