# Generated by Django 4.0.6 on 2022-07-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_review'),
    ]

    operations = [
        migrations.RunSQL("""
        ALTER TABLE playground_product
        ADD title VARCHAR(255);
        """)
    ]
